coverage:
  status:
    patch:
      default:
        branches:
          - "!main"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

