name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run test
        run: |
          go test -v
